permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      pythonver:
        default: '3.13.1'
      preset:
        type: choice
        options: 
        - PyFoundation
        - ExtWin7adang1345
jobs:
  get-package-push:
    runs-on: windows-2025
    env:
      PresetsMappingJson: |
        {
        "PyFoundation":
          {"instexeformat": "python-{0}-amd64.exe", "insturlformat": "https://www.python.org/ftp/python/{0}", "branchformat": "{0}-win64"},
        "ExtWin7adang1345":
          {"instexeformat": "python-{0}-amd64-full.exe", "insturlformat": "https://github.com/adang1345/PythonWin7/raw/refs/heads/master/{0}", "branchformat": "{0}-ext64"}
        }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloaded
          path: downloaded/
      - run: |
          .github\get-and-expand-python.ps1 -pythoninstcacheprefix ${{ inputs.preset }} -pythoninstexe ${{ format(fromJson(env.PresetsMappingJson)[inputs.preset]['instexeformat'], inputs.pythonver) }} -pythoninsturl ${{ format(fromJson(env.PresetsMappingJson)[inputs.preset]['insturlformat'], inputs.pythonver)}}
          # .github\expanded\python.exe .github\package-python.py ${{ format(fromJson(env.PresetsMappingJson)[inputs.preset]['branchformat'], inputs.pythonver)}}
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5  # v9.1.4
        with:
          remove: "-r --cached --quiet .github downloaded"
          message: "Github action build ${{ format(fromJson(env.PresetsMappingJson)[inputs.preset]['branchformat'], inputs.pythonver) }}"
          push: origin HEAD:${{ format(fromJson(env.PresetsMappingJson)[inputs.preset]['branchformat'], inputs.pythonver) }} --force