name: ci
on:
  workflow_dispatch:
    inputs:
      pythonver:
        default: '3.13.1'
jobs:
  get-and-package-python:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloaded
          path: |
            downloaded/
      - run: .\get-and-expand-python.ps1 -pythonver ${{ github.event.inputs.pythonver }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Main installer expanded
          path: expanded
      - run: expanded\python.exe .\package-python.py
      - uses: actions/upload-artifact@v4
        with:
          name: Portable-pip-python64-win
          path: artifacts


