name: ci
on:
  workflow_dispatch:
    inputs:
      pythonver:
        default: '3.13.1'
jobs:
  get-and-package-python:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloaded
          path: |
            downloaded/
      - run: .github\get-and-expand-python.ps1 -pythoninstexe python-${{ github.event.inputs.pythonver }}-amd64-full.exe -pythoninsturl https://github.com/adang1345/PythonWin7/raw/refs/heads/master/${{ github.event.inputs.pythonver }}
      - run: .github\expanded\python.exe .github\package-python.py
      - uses: actions/upload-artifact@v4
        with:
          name: Portable-pip-python64-win
          path: artifacts


