name: ci
on:
  workflow_dispatch:
    inputs:
      pythonver:
        default: '3.13.1'
      pythoninstexeformat:
        default: 'python-{0}-amd64-full.exe'
      pythoninsturlformat:
        default: 'https://github.com/adang1345/PythonWin7/raw/refs/heads/master/{0}'
      releasebranchformat:
        default: 'PIPinZIP-win64-{0}'
jobs:
  get-and-package-python:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloaded
          path: |
            downloaded/
      - run: |
          .github\get-and-expand-python.ps1 -pythoninstexe ${{ format(github.event.inputs.pythoninstexeformat, github.event.inputs.pythonver)}} -pythoninsturl ${{ format(github.event.inputs.pythoninsturlformat, github.event.inputs.pythonver)}}
          .github\expanded\python.exe .github\package-python.py
      - uses: actions/upload-artifact@v4
        with:
          name: PIPinZIP
          path: .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5: #v9.1.4
        with:
          push: origin ${{ format(github.event.inputs.releasebranchformat, github.event.inputs.pythonver)}} --force
          remove: "-r --cached .github"



