name: ci
on:
  push:
    branches:
      - '*'
    tags:
      - '**'
  pull_request:
    branches:
      - '*'
jobs:
  get-and-package-python:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloaded
          path: |
            downloaded/
      - run: |
          .\get-and-expand-python.ps1 -pythonver 3.13.0
          .\package-python.py.bat
        shell: powershell

